# -*- coding: utf-8 -*-
"""Stone paper scissors

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NCRae4HjD1eBebz3rqSVFzHHDe9TjHy5
"""

import random
def get_choices():
  player=input("Enter a choice(rock,paper,scissors):")
  options=['rock','paper','scissors']
  computer=random.choice(options)
  choices={'player':player,'computer':computer}
  return choices
def check_win(player,computer):
  print("You chose " + player , 'computer chose ' + computer)
  if player==computer:
    return "It's a tie"
  elif player=='rock':
    if computer=='scissors':
      return 'rock smashes scissors, you win!!!!'
    else:
      return ' paper covers rock , you lose!!!'
  elif player=='paper':
    if computer=='rock':
      return 'paper covers rock, you win!!!!'
    else:
      return 'scissors cuts paper, you lose!!!'
  elif player=='scissors':
    if computer=='paper':
      return 'scissors cuts paper, you win!!!!'
    else:
      return 'rock smashes paper, you lose!!!'
choices=get_choices()
result=check_win(choices["player"],choices["computer"])
print(result)